### ISSUE TITLE
[Bug] Cannot find module 'libnpx'

### ISSUE THREAD

**Issue by SaraVieira** [jxnblk/ram#8]
Hey !
This looks awesome and it works when I download the latest version but i forked it and tried to run it in my computer to add some more options and I get this error :(

<img width="880" alt="screen shot 2018-06-04 at 18 51 05" src="https://user-images.githubusercontent.com/1051509/40933062-47aee482-6828-11e8-94eb-cbb16c33001f.png">

```
npx create-react-app swinternal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module 'libnpx'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npx-cli.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

Has this happened to you ?

**Comment by jxnblk** [comment]
Thanks! Do you mind checking what version of npm you have installed by running: `npm -v` in your terminal?

**Comment by SaraVieira** [comment]
Soooo... Apparently my npm was broken and not your app. That was weird.

Sorry :(

**Comment by jxnblk** [comment]
No worries! Glad you got it sorted out :)
